spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    database: mysql
    show-sql: true 
    generate-ddl: false
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        type: trace
        jdbc:
          time_zone: GMT    
  datasource:
    url: jdbc:mysql://localhost:3306/contact_management_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: Nikunj#15
    driverClassName: com.mysql.jdbc.Driver
##################################################################
# LOGGING LEVELS
##################################################################        
logging:
  level:
    org:
      hibernate: 
        type:  
          descriptor: 
            sql: 
              BasicBinder: TRACE 
              
server:
  port: 8083
upload:
  Path: ./